import numpy as np
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
x_cube_m=np.multiply(x,np.multiply(x,x))
x_cube_op=x*x*x
x_cube_pow=np.power(x,3)
x_cube_d_s=x**3
identity_mat=np.identity(x.shape[0])
x_pow_2=np.power(x,2)
x_pow_3=np.power(x,3)
x_cube_4=np.power(x,4)
print("Jaison Jacob \n23mca033\ncycle2_pgm11")
print("\nOrginal Matrix:")
print(x)
print("\nCubed Matrix method1:")
print(x_cube_m)
print("\nCubed Matrix method2:")
print(x_cube_op)
print("\nCubed Matrix method3:")
print(x_cube_pow)
print("\nCubed Matrix method4:")
print(x_cube_d_s)
print("\nIdentity Matrix:")
print(identity_mat)
print("\n Matrix to Different power:")
print("X^2:")
print(x_pow_2)
print("X^3:")
print(x_pow_3)
print("X^4:")
print(x_cube_4)
